version: '3'
services:
  app:
    image: python:3.9-slim
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 200M

